#!/usr/bin/env bash
# profile.sh — resolve composable capabilities into per-project .claude/ config.
#
#   nb profile list              show all capability layers
#   nb profile show <path>       what a given project resolves to
#   nb profile apply <path>      generate that project's .claude/ config
#   nb profile sync              apply to every path in config/profiles.json
#   nb profile check             report projects with no profile defined
#
set -uo pipefail
R="$(cd "$(dirname "$0")/.." && pwd)"
PROJECTS="$HOME/Projects"

python3 - "$R" "$PROJECTS" "$@" <<'PY'
import json, os, sys, glob, re

R, PROJECTS = sys.argv[1], sys.argv[2]
args = sys.argv[3:]
cmd = args[0] if args else "list"

B, D, G, Y, X = "\033[1m", "\033[2m", "\033[32m", "\033[33m", "\033[0m"

def load_yaml_lite(p):
    """Minimal YAML reader for our flat capability files."""
    out, key, buf = {}, None, []
    for line in open(p):
        if line.startswith("guidance:"):
            key = "guidance"; buf = []; continue
        if key == "guidance":
            if line.startswith("  ") or not line.strip():
                buf.append(line[2:].rstrip("\n")); continue
            out["guidance"] = "\n".join(buf).strip(); key = None
        m = re.match(r"^(\w+):\s*(.*)$", line)
        if m:
            k, v = m.group(1), m.group(2).strip()
            out[k] = [] if v == "[]" else (v if v else [])
            key = k if not v else None
        elif line.strip().startswith("- ") and key:
            out.setdefault(key, [])
            if isinstance(out[key], list): out[key].append(line.strip()[2:])
    if key == "guidance": out["guidance"] = "\n".join(buf).strip()
    return out

caps = {}
for f in glob.glob(f"{R}/capabilities/*.yaml"):
    c = load_yaml_lite(f)
    if c.get("name"): caps[c["name"]] = c

prof = json.load(open(f"{R}/config/profiles.json"))
paths, universal = prof["paths"], prof.get("universal", {})

def resolve(path):
    """Longest matching prefix wins; that entry's capabilities are used."""
    best, best_len = None, -1
    for p in paths:
        if (path == p or path.startswith(p + "/")) and len(p) > best_len:
            best, best_len = p, len(p)
    if best is None: return None, []
    return best, paths[best].get("capabilities", [])

def collect(names):
    skills, plugins, mcp, guide = [], [], [], []
    for n in names:
        c = caps.get(n)
        if not c:
            print(f"  {Y}warning: unknown capability '{n}'{X}"); continue
        for k, dst in (("skills", skills), ("plugins", plugins), ("mcp", mcp)):
            v = c.get(k) or []
            if isinstance(v, list): dst.extend(v)
        if c.get("guidance"): guide.append((n, c["guidance"]))
    plugins += universal.get("plugins", []) or []
    skills += universal.get("skills", []) or []
    return sorted(set(skills)), sorted(set(plugins)), sorted(set(mcp)), guide

def apply(path):
    matched, names = resolve(path)
    if matched is None:
        print(f"  {Y}no profile defined for {path}{X}"); return False
    full = os.path.join(PROJECTS, path)
    if not os.path.isdir(full):
        print(f"  {D}skip (missing): {path}{X}"); return False
    skills, plugins, mcp, guide = collect(names)

    cdir = os.path.join(full, ".claude")
    os.makedirs(cdir, exist_ok=True)

    # settings.json — merge, never clobber user keys
    sp = os.path.join(cdir, "settings.json")
    settings = {}
    if os.path.exists(sp):
        try: settings = json.load(open(sp))
        except Exception: settings = {}
    settings["enabledPlugins"] = {f"{p}": True for p in plugins}
    json.dump(settings, open(sp, "w"), indent=2)

    # symlink ONLY this project's skills from nathanbot/skills
    sk_dir = os.path.join(cdir, "skills")
    os.makedirs(sk_dir, exist_ok=True)
    for existing in os.listdir(sk_dir):
        ep = os.path.join(sk_dir, existing)
        if os.path.islink(ep) and existing not in skills:
            os.unlink(ep)          # stale link from a previous profile
    for s in skills:
        src = os.path.join(R, "skills", s)
        dst = os.path.join(sk_dir, s)
        # lexists, not exists: exists() follows the link, so a DANGLING link whose
        # name is still profiled looked absent, os.symlink raised FileExistsError,
        # and — sync has no try/except around apply() — every remaining project
        # went unconfigured. Unlink and relink rather than skip, so a link pointing
        # at the wrong place is repaired too.
        if os.path.isdir(src):
            if os.path.islink(dst):
                os.unlink(dst)
            if not os.path.lexists(dst):
                os.symlink(src, dst)

    # generated guidance file — capabilities explain themselves to the agent
    gp = os.path.join(cdir, "CAPABILITIES.md")
    with open(gp, "w") as fh:
        fh.write(f"# Capabilities — {path}\n\n")
        fh.write("<!-- GENERATED by `nb profile apply`. Edit capability files in\n")
        fh.write("     nathanbot/capabilities/, not this file. -->\n\n")
        fh.write(f"Composed layers: {', '.join(names)}\n\n")
        for n, g in guide:
            fh.write(f"## {n}\n{g}\n\n")
        if skills:
            fh.write(f"## Skills available here\n{', '.join(skills)}\n\n")
    print(f"  {G}✓{X} {path:<42} {D}{len(names)} layers · {len(plugins)} plugins · {len(skills)} skills{X}")
    return True

if cmd == "list":
    print(f"{B}Capability layers{X}")
    for kind in ("language", "framework", "platform", "domain", "practice"):
        group = [c for c in caps.values() if c.get("kind") == kind]
        if not group: continue
        print(f"\n  {B}{kind}{X}")
        for c in sorted(group, key=lambda x: x["name"]):
            print(f"    {c['name']:<24} {D}{c.get('description','')}{X}")

elif cmd == "show":
    if len(args) < 2: sys.exit("usage: nb profile show <path>")
    path = args[1].replace(PROJECTS + "/", "").strip("/")
    matched, names = resolve(path)
    if matched is None: sys.exit(f"no profile for {path}")
    skills, plugins, mcp, guide = collect(names)
    print(f"{B}{path}{X}  {D}(matched rule: {matched}){X}")
    print(f"  layers:  {', '.join(names)}")
    print(f"  plugins: {', '.join(plugins) or '-'}")
    print(f"  skills:  {', '.join(skills) or '-'}")
    print(f"  mcp:     {', '.join(mcp) or '-'}")

elif cmd == "apply":
    if len(args) < 2: sys.exit("usage: nb profile apply <path>")
    apply(args[1].replace(PROJECTS + "/", "").strip("/"))

elif cmd == "sync":
    print(f"{B}Applying profiles to all defined paths{X}")
    n = sum(1 for p in sorted(paths) if apply(p))
    print(f"\n{G}{n} project(s) configured{X}")

elif cmd == "check":
    print(f"{B}Projects with no profile{X}")
    missing = 0
    for d in sorted(glob.glob(f"{PROJECTS}/*/")):
        name = os.path.basename(d.rstrip("/"))
        if name.startswith("."): continue
        if resolve(name)[0] is None:
            print(f"  {Y}•{X} {name}"); missing += 1
        for sub in sorted(glob.glob(f"{d}*/")):
            if not os.path.isdir(os.path.join(sub, ".git")): continue
            rel = os.path.relpath(sub.rstrip("/"), PROJECTS)
            if resolve(rel)[0] is None:
                print(f"  {Y}•{X} {rel}"); missing += 1
    print(f"\n{D}{missing} unprofiled{X}" if missing else f"{G}all covered{X}")
else:
    sys.exit(f"unknown: {cmd}")
PY
