#!/usr/bin/env python3
"""Generate wiki/index.md from page frontmatter, and lint the wiki against SCHEMA.md.

Why generated: the index is read by every agent as plain text (Dataview queries render
only inside Obsidian, so agents would see the query, not the answer). Keeping it as a
real markdown list means both humans and agents read the same thing — but hand-editing
it drifts, so it is rebuilt from the pages themselves.
"""
from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
PAGES = WIKI / "pages"
INDEX = WIKI / "index.md"

# Order sections appear in the index. Anything with an unknown type lands in "Other".
TYPE_ORDER = ["person", "project", "entity", "strategy", "reference", "decision"]
TYPE_HEADING = {
    "person": "Person",
    "project": "Projects",
    "entity": "Ventures & entities",
    "strategy": "Strategy",
    "reference": "Reference",
    "decision": "Decisions",
    "other": "Other",
}
REQUIRED_KEYS = ("title", "type", "status", "updated")
VALID_TYPES = set(TYPE_ORDER)
VALID_STATUS = {"active", "dormant", "archived"}

HEADER = """# Wiki Index

Directory of durable knowledge pages. Open only what a task needs.
Schema: `SCHEMA.md`. Storage routing: `storage-policy.md`.

<!-- GENERATED by `nb wiki index` — do not hand-edit; edit the pages' frontmatter instead. -->
"""


def parse(path: Path) -> dict:
    """Split a page into frontmatter dict + body, tolerating missing frontmatter."""
    text = path.read_text(encoding="utf-8")
    fm, body = {}, text
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end != -1:
            for line in text[4:end].splitlines():
                if ":" in line:
                    k, _, v = line.partition(":")
                    fm[k.strip()] = v.strip()
            body = text[end + 4:]
    return {"path": path, "slug": path.stem, "fm": fm, "body": body}


def summary(page: dict, limit: int = 110) -> str:
    """First sentence of the body — SCHEMA says the opening line is the one-line definition.

    Unwraps the first paragraph before cutting, so a hard-wrapped opener does not get
    truncated mid-clause.
    """
    if page["fm"].get("summary"):  # explicit override wins — for pages whose opener is weak
        return page["fm"]["summary"].strip().rstrip(".")

    para: list[str] = []
    for line in page["body"].splitlines():
        line = line.strip()
        if not line or line.startswith(("#", "<!--", "```", "-", "|", ">")):
            if para:
                break
            continue
        para.append(line)
    if not para:
        return ""

    text = re.sub(r"\*\*(.+?)\*\*", r"\1", " ".join(para))
    first = re.split(r"(?<=[.!?])\s", text)[0].strip()
    if len(first) <= limit:
        return first.rstrip(".")
    return first[:limit].rsplit(" ", 1)[0].rstrip(" .,;:—-") + "…"


def load() -> list[dict]:
    return [parse(p) for p in sorted(PAGES.glob("*.md")) if not p.name.startswith("_")]


def render(pages: list[dict]) -> str:
    buckets: dict[str, list[dict]] = {}
    for p in pages:
        t = p["fm"].get("type", "other")
        buckets.setdefault(t if t in VALID_TYPES else "other", []).append(p)

    out = [HEADER]
    for t in TYPE_ORDER + ["other"]:
        group = buckets.get(t)
        if not group:
            continue
        # active first, then alphabetical — dead things sink to the bottom of their section
        group.sort(key=lambda p: (p["fm"].get("status") != "active", p["slug"]))
        out.append(f"\n## {TYPE_HEADING[t]}")
        for p in group:
            note = summary(p)
            status = p["fm"].get("status", "?")
            tail = "" if status == "active" else f" *({status})*"
            out.append(f"- [[{p['slug']}]] — {note}{tail}" if note else f"- [[{p['slug']}]]{tail}")
    out.append("")
    return "\n".join(out)


def lint(pages: list[dict]) -> list[str]:
    problems = []
    slugs = {p["slug"] for p in pages}
    # pages living at the wiki root are addressable too (task-style, storage-policy, ...)
    slugs |= {p.stem for p in WIKI.glob("*.md")}
    slugs |= {p.stem for p in (WIKI / "daily").glob("*.md")}

    for p in pages:
        where = f"wiki/pages/{p['path'].name}"
        for key in REQUIRED_KEYS:
            if key not in p["fm"]:
                problems.append(f"{where}: missing frontmatter `{key}:`")
        t, s = p["fm"].get("type"), p["fm"].get("status")
        if t and t not in VALID_TYPES:
            problems.append(f"{where}: type `{t}` not in {sorted(VALID_TYPES)}")
        if s and s not in VALID_STATUS:
            problems.append(f"{where}: status `{s}` not in {sorted(VALID_STATUS)}")
        if re.match(r"^\d{4}-\d{2}-\d{2}", p["slug"]):
            problems.append(f"{where}: dated filename — daily notes belong in wiki/daily/")
        if not p["body"].strip():
            problems.append(f"{where}: empty page")
        if not re.search(r"\[\[[^\]]+\]\]", strip_code(p["body"])):
            problems.append(f"{where}: orphan — links to nothing (SCHEMA: every page links out)")

    # dead links, ignoring anything inside code spans/fences (docs quote link syntax)
    for md in sorted(WIKI.rglob("*.md")):
        if any(part.startswith(".") or part == "raw" for part in md.parts):
            continue
        for target in re.findall(r"\[\[([^\]|#]+)", strip_code(md.read_text(encoding="utf-8"))):
            if target.strip() not in slugs and target.strip() != "index":
                problems.append(f"{md.relative_to(ROOT)}: dead link [[{target.strip()}]]")

    stale = [p for p in pages if p["fm"].get("status") == "active"
             and p["fm"].get("updated", "") < str(date.today().replace(year=date.today().year - 1))]
    for p in stale:
        problems.append(f"wiki/pages/{p['path'].name}: active but not updated in over a year")
    return problems


def strip_code(text: str) -> str:
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    return re.sub(r"`[^`]*`", "", text)


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "--write"
    pages = load()

    if mode in ("--lint", "--check"):
        problems = lint(pages)
        drift = render(pages) != INDEX.read_text(encoding="utf-8")
        if drift:
            problems.append("wiki/index.md: out of date — run `nb wiki index`")
        for p in problems:
            print(p)
        print(f"\n{len(pages)} pages, {len(problems)} problem(s)")
        return 1 if problems and mode == "--check" else 0

    INDEX.write_text(render(pages), encoding="utf-8")
    print(f"wrote wiki/index.md ({len(pages)} pages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
